# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
G_mat_cpp <- function(M, inverse = FALSE) {
    .Call(`_GOplan_G_mat_cpp`, M, inverse)
}

mc_cpp <- function(nplan, fPath) {
    invisible(.Call(`_GOplan_mc_cpp`, nplan, fPath))
}

